### PR TITLE
update bootstrap function with es6 and pathJoin

### PR DESCRIPTION
**Pull request by jaydray1**
Am I doing this right? Never done a PR on a github repo like this - I thought it would be nice to have this updated with es6 :)

### CODE REVIEW

**Review by cwadrupldijjit — COMMENTED** [review]
I'm hesitant to accept a PR like this for this repository for a few reasons:

1. This would be a breaking change.  Node does allow for ES6 modules now, but it doesn't work with this approach, primarily because there are more changes needed before it will work.
1. Not all features of ES6 are necessary to be used at all time.  There is absolutely no reason to change the `function` definition to a `const` variable with a function expression.  That, in fact, is my one biggest problem with the popularized way of doing things--there is no reason to turn it into a constant variable.  We're also not using `this`, so the argument of using an arrow function is not a compelling enough reason to change.
1. I would like to keep this repository fairly similar to how the DevMountain Cohort that I made it for would remember it so they can refer to it if they need.  Indeed, they could probably still read it, but I'm not sure that I'd agree with changing it yet.

**Comment by jaydray1** [comment]
Yeah I wouldn't argue with the this binding argument - the only argument I'd make in general for updating to const with function definition would be modernization of new language features, which as you pointed out, is no reason to modify in one file if not planning on modifying in all, and yes, hasty change on the modules update without regards to the rest of the app.

**Comment by cwadrupldijjit** [comment]
Thanks for wanting to contribute, though!  I'm glad you're eager to contribute!

**Comment by jaydray1** [comment]
Yes! Yeah, I'd like to contribute more to projects and I won't get better
at the language and paradigms if I don't attempt working with others - love
the feedback!

Jon-Michael Dreher
c. 385.242.1497
e. jdreher15@gmail.com

**Pull request closed without merging**
